modules={'1':[{"module":"test_module1",
              "show_module":"yes"},
             {"module":"test_module2",
              "show_module":"no"}
             ],
         '2':["molule1"],
         '3':["module2"]}
modulesLessons={'1':{"test_module1":[
    {"lesson":'ielts_read_1.0',
     "show_lesson":"yes"},
    {"lesson":'ielts_read_1.0.1',
     "show_lesson":"yes"},
    {"lesson":'verbs',
     "show_lesson":"yes"}],
                     "test_modele2":[]},
         '2':["molule1"],
         '3':["module2"]}
